only_rules:
- anyobject_protocol
- block_based_kvo
- class_delegate_protocol
- closing_brace
- closure_end_indentation
- closure_parameter_position
- closure_spacing
- collection_alignment
- colon
- comma
- comment_spacing
- compiler_protocol_init
- computed_accessors_order
- contains_over_filter_count
- contains_over_filter_is_empty
- contains_over_first_not_nil
- contains_over_range_nil_comparison
- control_statement
- custom_rules
- deployment_target
- discouraged_assert
- discouraged_direct_init
- duplicate_enum_cases
- duplicate_imports
- dynamic_inline
- empty_collection_literal
- empty_count
- empty_enum_arguments
- empty_parameters
- empty_parentheses_with_trailing_closure
- empty_string
- empty_xctest_method
- expiring_todo
- fatal_error_message
- file_length
- file_name_no_space
- for_where
- identical_operands
- implicit_return
- inert_defer
- is_disjoint
- large_tuple
- last_where
- leading_whitespace
- legacy_cggeometry_functions
- legacy_constant
- legacy_constructor
- legacy_hashing
- legacy_nsgeometry_functions
- legacy_random
- literal_expression_end_indentation
- lower_acl_than_parent
- mark
- multiline_literal_brackets
- multiline_parameters
- multiple_closures_with_trailing_closure
- no_extension_access_modifier
- no_fallthrough_only
- no_space_in_method_call
- nsobject_prefer_isequal
- operator_usage_whitespace
- operator_whitespace
- orphaned_doc_comment
- overridden_super_call
- override_in_extension
- prefer_self_type_over_type_of_self
- prefer_zero_over_explicit_init
- private_over_fileprivate
- private_unit_test
- prohibited_super_call
- protocol_property_accessors_order
- reduce_boolean
- reduce_into
- redundant_discardable_let
- redundant_objc_attribute
- redundant_optional_initialization
- redundant_set_access_control
- redundant_string_enum_value
- redundant_void_return
- required_enum_case
- return_arrow_whitespace
- sorted_first_last
- sorted_imports
- statement_position
- superfluous_disable_command
- switch_case_alignment
- toggle_bool
- trailing_comma
- trailing_newline
- trailing_semicolon
- trailing_whitespace
- unneeded_break_in_switch
- unused_capture_list
- unused_closure_parameter
- unused_control_flow_label
- unused_enumerated
- unused_import
- unused_optional_binding
- unused_setter_value
- vertical_parameter_alignment
- vertical_parameter_alignment_on_call
- vertical_whitespace
- vertical_whitespace_closing_braces
- void_return
- weak_delegate
- xct_specific_matcher
- xctfail_message
- yoda_condition
excluded:
  - .build/
  - Blockchain/JavaScript/
  - Carthage/
  - DerivedData/
  - KitchenSink/
  - Modules/*/.build/
  - Modules/*/*.generated.swift
  - Modules/BlockchainNamespace/Sources/BlockchainNamespace/blockchain.swift
  - scripts/*/.build/
  - SourcePackages/
  - Submodules/
  - vendor/bundle
file_length:
  warning: 1600
  error: 1800
deployment_target:
  iOS_deployment_target: 14.0
empty_count:
  severity: warning
no_extension_access_modifier:
  severity: warning
large_tuple:
  warning: 5
  error: 6
